name: ET3
favicon: null
layout_spectrum: 0.56296277907677
typography_spectrum: 0.9983798286411911
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00bf00'
    - '#3b79b2'
    - '#e5e5e3'
    - '#171a11'
    - '#9baa4f'
  brandStrength: 0.5
  lightness: 0.7969734601210803
  saturation: 0.125
  rhythmicContrast: 0.21172881172969937
purpose: []
